### ISSUE TITLE
Trigger keyword conflict and docvue snippets error

### ISSUE THREAD

**Issue by realstephenzhao** [yesilfasulye/sublime_html_page_snippets#3]
## Trigger keyword conflict
HTML Page Snippets' Blank HTML Page tabTrigger keyword "doc" is in conflict with Emmet's "doc":

![Trigger keyword conflict](https://cloud.githubusercontent.com/assets/7487908/26151939/7ebf1f92-3b37-11e7-8805-075c1ce6b0d4.gif)

*I hope you can change "doc" to other words like "docu" or "doch" which can perform well.*

## HTML Page with VueJS snippet issue
This is an error detected by auto syntax check of Sublimelinter, you see it below:

![HTML Page with VueJS snippet issue](https://cloud.githubusercontent.com/assets/7487908/26161998/153c5212-3b58-11e7-861d-e0c8ae4ac061.png)

*It seems lacking of a semicolon sign right beside the closing parenthesis in line 21. After I add one, it just works fine with no errors.*

**Comment by yesilfasulye** [comment]
Thank you for feedback. Both files have been updated...
