### ISSUE TITLE
UPDATE PLEASE & THANK YOU

### ISSUE THREAD

**Issue by ghost** [yesilfasulye/sublime_html_page_snippets#4]
I went to MaxCDN and did pull their latest and greatest. Running Safari from macOS 10.13.1

(not my Kali)
Someone came on board and tidied up bootstrap to makes all 5 snippets more light-weight. 

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">`

WHITE HACK

`<html>`
`<head>`
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">`
`</head>`
`</html>`

ORGINAL SCRIPT

`<html>`
`<head>`
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">`
`</head>`
`<!-- jQuery first, then Tether, then Bootstrap JS. -->`
`<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>`
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>`
`</html>`

Styling with 4.0.0 big stability improvement over 3.7.0
I assume reversion to historical yesilfasulye layout indicates that yesilfasulye made good.
HTML Page Snippets at PackageControl.IO needs **4.0.0-alpha6 update** !!

Thank You ;-) 

[prv package resource viewer extraction]

**Comment by yesilfasulye** [comment]
Thank you for your feedback. Bootstrap link has been updated to **v4.0.0-beta.3**
